version: "3.8"
services:
  express:
    container_name: express
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/