version: "3.8"
services:
  rethinkdb:
    image: rethinkdb
    ports:
      - "9090:8080"
      - "28015:28015"
    volumes:
      - ~/apps/rethinkdb/data:/app
    networks:
      - swagger
  swagger:
    container_name: swagger_db
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "10010:10010"
    restart: unless-stopped
    volumes:
      - ./node_gallery/:/usr/src/docs/node_gallery/
    depends_on:
      - rethinkdb
    networks:
      - swagger
networks:
  swagger:
    name: swagger